services:
  - type: web
    name: Semantic-Recommendation-Service
    env: python
    buildCommand: pip install -r requirements.txt && python -c "from sentence_transformers import SentenceTransformer; SentenceTransformer('all-MiniLM-L6-v2')"
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PINECONE_KEY
        sync: false
      - key: GOOGLE_API_KEY
        sync: false
    plan: free
